// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'db_models.dart';

// **************************************************************************
// SqfEntityGenerator
// **************************************************************************

//  These classes was generated by SqfEntity
//  Copyright (c) 2019, All rights reserved. Use of this source code is governed by a
//  Apache license that can be found in the LICENSE file.

//  To use these SqfEntity classes do following:
//  - import model.dart into where to use
//  - start typing ex:Bookmark.select()... (add a few filters with fluent methods)...(add orderBy/orderBydesc if you want)...
//  - and then just put end of filters / or end of only select()  toSingle() / or toList()
//  - you can select one or return List<yourObject> by your filters and orders
//  - also you can batch update or batch delete by using delete/update methods instead of tosingle/tolist methods
//    Enjoy.. Huseyin Tokpunar

// ignore_for_file:
// BEGIN TABLES
// Bookmark TABLE
class TableBookmark extends SqfEntityTableBase {
  TableBookmark() {
    // declare properties of EntityTable
    tableName = 'bookmark';
    primaryKeyName = 'id';
    primaryKeyType = PrimaryKeyType.integer_auto_incremental;
    useSoftDeleting = true;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('title', DbType.text, isNotNull: false),
      SqfEntityFieldBase('imageUrl', DbType.text, isNotNull: false),
      SqfEntityFieldBase('sourceName', DbType.text, isNotNull: false),
      SqfEntityFieldBase('sourceImageUrl', DbType.text, isNotNull: false),
      SqfEntityFieldBase('content', DbType.text, isNotNull: false),
      SqfEntityFieldBase('dateTime', DbType.datetime,
          isNotNull: false, minValue: DateTime.parse('1900-01-01')),
    ];
    super.init();
  }
  static SqfEntityTableBase _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TableBookmark();
  }
}

// Cache TABLE
class TableCache extends SqfEntityTableBase {
  TableCache() {
    // declare properties of EntityTable
    tableName = 'cache';
    primaryKeyName = 'id';
    primaryKeyType = PrimaryKeyType.integer_auto_incremental;
    useSoftDeleting = false;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('title', DbType.text, isNotNull: false),
      SqfEntityFieldBase('imageUrl', DbType.text, isNotNull: false),
      SqfEntityFieldBase('sourceName', DbType.text, isNotNull: false),
      SqfEntityFieldBase('sourceImageUrl', DbType.text, isNotNull: false),
      SqfEntityFieldBase('content', DbType.text, isNotNull: false),
      SqfEntityFieldBase('dateTime', DbType.datetime,
          isNotNull: false, minValue: DateTime.parse('1900-01-01')),
    ];
    super.init();
  }
  static SqfEntityTableBase _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TableCache();
  }
}
// END TABLES

// BEGIN DATABASE MODEL
class DbModel extends SqfEntityModelProvider {
  DbModel() {
    databaseName = dbModel.databaseName;
    password = dbModel.password;
    dbVersion = dbModel.dbVersion;
    databaseTables = [
      TableBookmark.getInstance,
      TableCache.getInstance,
    ];

    bundledDatabasePath = dbModel
        .bundledDatabasePath; //'assets/sample.db'; // This value is optional. When bundledDatabasePath is empty then EntityBase creats a new database when initializing the database
  }
  Map<String, dynamic> getControllers() {
    final controllers = <String, dynamic>{};

    return controllers;
  }
}
// END DATABASE MODEL

// BEGIN ENTITIES
// region Bookmark
class Bookmark {
  Bookmark(
      {this.id,
      this.title,
      this.imageUrl,
      this.sourceName,
      this.sourceImageUrl,
      this.content,
      this.dateTime,
      this.isDeleted}) {
    _setDefaultValues();
  }
  Bookmark.withFields(this.title, this.imageUrl, this.sourceName,
      this.sourceImageUrl, this.content, this.dateTime, this.isDeleted) {
    _setDefaultValues();
  }
  Bookmark.withId(this.id, this.title, this.imageUrl, this.sourceName,
      this.sourceImageUrl, this.content, this.dateTime, this.isDeleted) {
    _setDefaultValues();
  }
  Bookmark.fromMap(Map<String, dynamic> o, {bool setDefaultValues = true}) {
    if (setDefaultValues) {
      _setDefaultValues();
    }
    id = int.tryParse(o['id'].toString());
    if (o['title'] != null) {
      title = o['title'] as String;
    }
    if (o['imageUrl'] != null) {
      imageUrl = o['imageUrl'] as String;
    }
    if (o['sourceName'] != null) {
      sourceName = o['sourceName'] as String;
    }
    if (o['sourceImageUrl'] != null) {
      sourceImageUrl = o['sourceImageUrl'] as String;
    }
    if (o['content'] != null) {
      content = o['content'] as String;
    }
    if (o['dateTime'] != null) {
      dateTime = int.tryParse(o['dateTime'].toString()) != null
          ? DateTime.fromMillisecondsSinceEpoch(
              int.tryParse(o['dateTime'].toString()))
          : DateTime.tryParse(o['dateTime'].toString());
    }
    isDeleted = o['isDeleted'] != null
        ? o['isDeleted'] == 1 || o['isDeleted'] == true
        : null;
  }
  // FIELDS (Bookmark)
  int id;
  String title;
  String imageUrl;
  String sourceName;
  String sourceImageUrl;
  String content;
  DateTime dateTime;
  bool isDeleted;

  BoolResult saveResult;
  // end FIELDS (Bookmark)

  static const bool _softDeleteActivated = true;
  BookmarkManager __mnBookmark;

  BookmarkManager get _mnBookmark {
    return __mnBookmark = __mnBookmark ?? BookmarkManager();
  }

  // METHODS
  Map<String, dynamic> toMap(
      {bool forQuery = false, bool forJson = false, bool forView = false}) {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (title != null) {
      map['title'] = title;
    }

    if (imageUrl != null) {
      map['imageUrl'] = imageUrl;
    }

    if (sourceName != null) {
      map['sourceName'] = sourceName;
    }

    if (sourceImageUrl != null) {
      map['sourceImageUrl'] = sourceImageUrl;
    }

    if (content != null) {
      map['content'] = content;
    }

    if (dateTime != null) {
      map['dateTime'] = forJson
          ? dateTime.toString()
          : forQuery ? dateTime.millisecondsSinceEpoch : dateTime;
    }

    if (isDeleted != null) {
      map['isDeleted'] = forQuery ? (isDeleted ? 1 : 0) : isDeleted;
    }

    return map;
  }

  Future<Map<String, dynamic>> toMapWithChildren(
      [bool forQuery = false,
      bool forJson = false,
      bool forView = false]) async {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (title != null) {
      map['title'] = title;
    }

    if (imageUrl != null) {
      map['imageUrl'] = imageUrl;
    }

    if (sourceName != null) {
      map['sourceName'] = sourceName;
    }

    if (sourceImageUrl != null) {
      map['sourceImageUrl'] = sourceImageUrl;
    }

    if (content != null) {
      map['content'] = content;
    }

    if (dateTime != null) {
      map['dateTime'] = forJson
          ? dateTime.toString()
          : forQuery ? dateTime.millisecondsSinceEpoch : dateTime;
    }

    if (isDeleted != null) {
      map['isDeleted'] = forQuery ? (isDeleted ? 1 : 0) : isDeleted;
    }

    return map;
  }

  /// This method returns Json String [Bookmark]
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method returns Json String [Bookmark]
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChildren(false, true));
  }

  List<dynamic> toArgs() {
    return [
      title,
      imageUrl,
      sourceName,
      sourceImageUrl,
      content,
      dateTime != null ? dateTime.millisecondsSinceEpoch : null,
      isDeleted
    ];
  }

  List<dynamic> toArgsWithIds() {
    return [
      id,
      title,
      imageUrl,
      sourceName,
      sourceImageUrl,
      content,
      dateTime != null ? dateTime.millisecondsSinceEpoch : null,
      isDeleted
    ];
  }

  static Future<List<Bookmark>> fromWebUrl(String url,
      {Map<String, String> headers}) async {
    try {
      final response = await http.get(url, headers: headers);
      return await fromJson(response.body);
    } catch (e) {
      print(
          'SQFENTITY ERROR Bookmark.fromWebUrl: ErrorMessage: ${e.toString()}');
      return null;
    }
  }

  Future<http.Response> postUrl(String url, {Map<String, String> headers}) {
    return http.post(url, headers: headers, body: toJson());
  }

  static Future<List<Bookmark>> fromJson(String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <Bookmark>[];
    try {
      objList = list
          .map((bookmark) => Bookmark.fromMap(bookmark as Map<String, dynamic>))
          .toList();
    } catch (e) {
      print('SQFENTITY ERROR Bookmark.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  static Future<List<Bookmark>> fromMapList(List<dynamic> data,
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields,
      bool setDefaultValues = true}) async {
    final List<Bookmark> objList = <Bookmark>[];
    loadedFields = loadedFields ?? [];
    for (final map in data) {
      final obj = Bookmark.fromMap(map as Map<String, dynamic>,
          setDefaultValues: setDefaultValues);

      objList.add(obj);
    }
    return objList;
  }

  /// returns Bookmark by ID if exist, otherwise returns null
  ///
  /// Primary Keys: int id
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: getById(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: getById(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>returns Bookmark if exist, otherwise returns null
  Future<Bookmark> getById(int id,
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    if (id == null) {
      return null;
    }
    Bookmark obj;
    final data = await _mnBookmark.getById([id]);
    if (data.length != 0) {
      obj = Bookmark.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the (Bookmark) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record

  /// <returns>Returns id
  Future<int> save() async {
    if (id == null || id == 0) {
      id = await _mnBookmark.insert(this);
    } else {
      // id= await _upsert(); // removed in sqfentity_gen 1.3.0+6
      await _mnBookmark.update(this);
    }

    return id;
  }

  /// saveAs Bookmark. Returns a new Primary Key value of Bookmark

  /// <returns>Returns a new Primary Key value of Bookmark
  Future<int> saveAs() async {
    id = null;

    return save();
  }

  /// saveAll method saves the sent List<Bookmark> as a bulk in one transaction
  ///
  /// Returns a <List<BoolResult>>
  static Future<List<dynamic>> saveAll(List<Bookmark> bookmarks) async {
    // final results = _mnBookmark.saveAll('INSERT OR REPLACE INTO bookmark (id,title, imageUrl, sourceName, sourceImageUrl, content, dateTime,isDeleted)  VALUES (?,?,?,?,?,?,?,?)',bookmarks);
    // return results; removed in sqfentity_gen 1.3.0+6
    await DbModel().batchStart();
    for (final obj in bookmarks) {
      await obj.save();
    }
    //    return DbModel().batchCommit();
    final result = await DbModel().batchCommit();
    for (int i = 0; i < bookmarks.length; i++) {
      if (bookmarks[i].id == null) {
        bookmarks[i].id = result[i] as int;
      }
    }

    return result;
  }

  /// Updates if the record exists, otherwise adds a new row

  /// <returns>Returns id
  Future<int> upsert() async {
    try {
      if (await _mnBookmark.rawInsert(
              'INSERT OR REPLACE INTO bookmark (id,title, imageUrl, sourceName, sourceImageUrl, content, dateTime,isDeleted)  VALUES (?,?,?,?,?,?,?,?)',
              [
                id,
                title,
                imageUrl,
                sourceName,
                sourceImageUrl,
                content,
                dateTime != null ? dateTime.millisecondsSinceEpoch : null,
                isDeleted
              ]) ==
          1) {
        saveResult = BoolResult(
            success: true,
            successMessage: 'Bookmark id=$id updated successfully');
      } else {
        saveResult = BoolResult(
            success: false, errorMessage: 'Bookmark id=$id did not update');
      }
      return id;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage: 'Bookmark Save failed. Error: ${e.toString()}');
      return 0;
    }
  }

  /// inserts or replaces the sent List<<Bookmark>> as a bulk in one transaction.
  ///
  /// upsertAll() method is faster then saveAll() method. upsertAll() should be used when you are sure that the primary key is greater than zero
  ///
  /// Returns a BoolCommitResult
  Future<BoolCommitResult> upsertAll(List<Bookmark> bookmarks) async {
    final results = await _mnBookmark.rawInsertAll(
        'INSERT OR REPLACE INTO bookmark (id,title, imageUrl, sourceName, sourceImageUrl, content, dateTime,isDeleted)  VALUES (?,?,?,?,?,?,?,?)',
        bookmarks);
    return results;
  }

  /// Deletes Bookmark

  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    print('SQFENTITIY: delete Bookmark invoked (id=$id)');
    if (!_softDeleteActivated || hardDelete || isDeleted) {
      return _mnBookmark
          .delete(QueryParams(whereString: 'id=?', whereArguments: [id]));
    } else {
      return _mnBookmark.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 1});
    }
  }

  /// Recover Bookmark>

  /// <returns>BoolResult res.success=Recovered, not res.success=Can not recovered
  Future<BoolResult> recover([bool recoverChilds = true]) async {
    print('SQFENTITIY: recover Bookmark invoked (id=$id)');
    {
      return _mnBookmark.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 0});
    }
  }

  BookmarkFilterBuilder select(
      {List<String> columnsToSelect, bool getIsDeleted}) {
    return BookmarkFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect;
  }

  BookmarkFilterBuilder distinct(
      {List<String> columnsToSelect, bool getIsDeleted}) {
    return BookmarkFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {
    isDeleted = isDeleted ?? false;
  }
  // END METHODS
  // CUSTOM CODES
  /*
      you must define customCode property of your SqfEntityTable constant for ex:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODES
}
// endregion bookmark

// region BookmarkField
class BookmarkField extends SearchCriteria {
  BookmarkField(this.bookmarkFB) {
    param = DbParameter();
  }
  DbParameter param;
  String _waitingNot = '';
  BookmarkFilterBuilder bookmarkFB;

  BookmarkField get not {
    _waitingNot = ' NOT ';
    return this;
  }

  BookmarkFilterBuilder equals(dynamic pValue) {
    param.expression = '=';
    bookmarkFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, bookmarkFB.parameters, param, SqlSyntax.EQuals,
            bookmarkFB._addedBlocks)
        : setCriteria(pValue, bookmarkFB.parameters, param, SqlSyntax.NotEQuals,
            bookmarkFB._addedBlocks);
    _waitingNot = '';
    bookmarkFB._addedBlocks.needEndBlock[bookmarkFB._blockIndex] =
        bookmarkFB._addedBlocks.retVal;
    return bookmarkFB;
  }

  BookmarkFilterBuilder equalsOrNull(dynamic pValue) {
    param.expression = '=';
    bookmarkFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, bookmarkFB.parameters, param,
            SqlSyntax.EQualsOrNull, bookmarkFB._addedBlocks)
        : setCriteria(pValue, bookmarkFB.parameters, param,
            SqlSyntax.NotEQualsOrNull, bookmarkFB._addedBlocks);
    _waitingNot = '';
    bookmarkFB._addedBlocks.needEndBlock[bookmarkFB._blockIndex] =
        bookmarkFB._addedBlocks.retVal;
    return bookmarkFB;
  }

  BookmarkFilterBuilder isNull() {
    bookmarkFB._addedBlocks = setCriteria(
        0,
        bookmarkFB.parameters,
        param,
        SqlSyntax.IsNULL.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        bookmarkFB._addedBlocks);
    _waitingNot = '';
    bookmarkFB._addedBlocks.needEndBlock[bookmarkFB._blockIndex] =
        bookmarkFB._addedBlocks.retVal;
    return bookmarkFB;
  }

  BookmarkFilterBuilder contains(dynamic pValue) {
    if (pValue != null) {
      bookmarkFB._addedBlocks = setCriteria(
          '%${pValue.toString()}%',
          bookmarkFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          bookmarkFB._addedBlocks);
      _waitingNot = '';
      bookmarkFB._addedBlocks.needEndBlock[bookmarkFB._blockIndex] =
          bookmarkFB._addedBlocks.retVal;
    }
    return bookmarkFB;
  }

  BookmarkFilterBuilder startsWith(dynamic pValue) {
    if (pValue != null) {
      bookmarkFB._addedBlocks = setCriteria(
          '${pValue.toString()}%',
          bookmarkFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          bookmarkFB._addedBlocks);
      _waitingNot = '';
      bookmarkFB._addedBlocks.needEndBlock[bookmarkFB._blockIndex] =
          bookmarkFB._addedBlocks.retVal;
      bookmarkFB._addedBlocks.needEndBlock[bookmarkFB._blockIndex] =
          bookmarkFB._addedBlocks.retVal;
    }
    return bookmarkFB;
  }

  BookmarkFilterBuilder endsWith(dynamic pValue) {
    if (pValue != null) {
      bookmarkFB._addedBlocks = setCriteria(
          '%${pValue.toString()}',
          bookmarkFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          bookmarkFB._addedBlocks);
      _waitingNot = '';
      bookmarkFB._addedBlocks.needEndBlock[bookmarkFB._blockIndex] =
          bookmarkFB._addedBlocks.retVal;
    }
    return bookmarkFB;
  }

  BookmarkFilterBuilder between(dynamic pFirst, dynamic pLast) {
    if (pFirst != null && pLast != null) {
      bookmarkFB._addedBlocks = setCriteria(
          pFirst,
          bookmarkFB.parameters,
          param,
          SqlSyntax.Between.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          bookmarkFB._addedBlocks,
          pLast);
    } else if (pFirst != null) {
      if (_waitingNot != '') {
        bookmarkFB._addedBlocks = setCriteria(pFirst, bookmarkFB.parameters,
            param, SqlSyntax.LessThan, bookmarkFB._addedBlocks);
      } else {
        bookmarkFB._addedBlocks = setCriteria(pFirst, bookmarkFB.parameters,
            param, SqlSyntax.GreaterThanOrEquals, bookmarkFB._addedBlocks);
      }
    } else if (pLast != null) {
      if (_waitingNot != '') {
        bookmarkFB._addedBlocks = setCriteria(pLast, bookmarkFB.parameters,
            param, SqlSyntax.GreaterThan, bookmarkFB._addedBlocks);
      } else {
        bookmarkFB._addedBlocks = setCriteria(pLast, bookmarkFB.parameters,
            param, SqlSyntax.LessThanOrEquals, bookmarkFB._addedBlocks);
      }
    }
    _waitingNot = '';
    bookmarkFB._addedBlocks.needEndBlock[bookmarkFB._blockIndex] =
        bookmarkFB._addedBlocks.retVal;
    return bookmarkFB;
  }

  BookmarkFilterBuilder greaterThan(dynamic pValue) {
    param.expression = '>';
    bookmarkFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, bookmarkFB.parameters, param,
            SqlSyntax.GreaterThan, bookmarkFB._addedBlocks)
        : setCriteria(pValue, bookmarkFB.parameters, param,
            SqlSyntax.LessThanOrEquals, bookmarkFB._addedBlocks);
    _waitingNot = '';
    bookmarkFB._addedBlocks.needEndBlock[bookmarkFB._blockIndex] =
        bookmarkFB._addedBlocks.retVal;
    return bookmarkFB;
  }

  BookmarkFilterBuilder lessThan(dynamic pValue) {
    param.expression = '<';
    bookmarkFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, bookmarkFB.parameters, param, SqlSyntax.LessThan,
            bookmarkFB._addedBlocks)
        : setCriteria(pValue, bookmarkFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, bookmarkFB._addedBlocks);
    _waitingNot = '';
    bookmarkFB._addedBlocks.needEndBlock[bookmarkFB._blockIndex] =
        bookmarkFB._addedBlocks.retVal;
    return bookmarkFB;
  }

  BookmarkFilterBuilder greaterThanOrEquals(dynamic pValue) {
    param.expression = '>=';
    bookmarkFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, bookmarkFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, bookmarkFB._addedBlocks)
        : setCriteria(pValue, bookmarkFB.parameters, param, SqlSyntax.LessThan,
            bookmarkFB._addedBlocks);
    _waitingNot = '';
    bookmarkFB._addedBlocks.needEndBlock[bookmarkFB._blockIndex] =
        bookmarkFB._addedBlocks.retVal;
    return bookmarkFB;
  }

  BookmarkFilterBuilder lessThanOrEquals(dynamic pValue) {
    param.expression = '<=';
    bookmarkFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, bookmarkFB.parameters, param,
            SqlSyntax.LessThanOrEquals, bookmarkFB._addedBlocks)
        : setCriteria(pValue, bookmarkFB.parameters, param,
            SqlSyntax.GreaterThan, bookmarkFB._addedBlocks);
    _waitingNot = '';
    bookmarkFB._addedBlocks.needEndBlock[bookmarkFB._blockIndex] =
        bookmarkFB._addedBlocks.retVal;
    return bookmarkFB;
  }

  BookmarkFilterBuilder inValues(dynamic pValue) {
    bookmarkFB._addedBlocks = setCriteria(
        pValue,
        bookmarkFB.parameters,
        param,
        SqlSyntax.IN.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        bookmarkFB._addedBlocks);
    _waitingNot = '';
    bookmarkFB._addedBlocks.needEndBlock[bookmarkFB._blockIndex] =
        bookmarkFB._addedBlocks.retVal;
    return bookmarkFB;
  }
}
// endregion BookmarkField

// region BookmarkFilterBuilder
class BookmarkFilterBuilder extends SearchCriteria {
  BookmarkFilterBuilder(Bookmark obj) {
    whereString = '';
    qparams = QueryParams();
    parameters = <DbParameter>[];
    orderByList = <String>[];
    groupByList = <String>[];
    _addedBlocks = AddedBlocks(<bool>[], <bool>[]);
    _addedBlocks.needEndBlock.add(false);
    _addedBlocks.waitingStartBlock.add(false);
    _pagesize = 0;
    _page = 0;
    _obj = obj;
  }
  AddedBlocks _addedBlocks;
  int _blockIndex = 0;
  List<DbParameter> parameters;
  List<String> orderByList;
  Bookmark _obj;
  QueryParams qparams;
  int _pagesize;
  int _page;

  /// put the sql keyword 'AND'
  BookmarkFilterBuilder get and {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' AND ';
    }
    return this;
  }

  /// put the sql keyword 'OR'
  BookmarkFilterBuilder get or {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' OR ';
    }
    return this;
  }

  /// open parentheses
  BookmarkFilterBuilder get startBlock {
    _addedBlocks.waitingStartBlock.add(true);
    _addedBlocks.needEndBlock.add(false);
    _blockIndex++;
    if (_blockIndex > 1) {
      _addedBlocks.needEndBlock[_blockIndex - 1] = true;
    }
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  BookmarkFilterBuilder where(String whereCriteria, {dynamic parameterValue}) {
    if (whereCriteria != null && whereCriteria != '') {
      final DbParameter param = DbParameter(
          columnName: parameterValue == null ? null : '',
          hasParameter: parameterValue != null);
      _addedBlocks = setCriteria(parameterValue ?? 0, parameters, param,
          '($whereCriteria)', _addedBlocks);
      _addedBlocks.needEndBlock[_blockIndex] = _addedBlocks.retVal;
    }
    return this;
  }

  /// page = page number,
  ///
  /// pagesize = row(s) per page
  BookmarkFilterBuilder page(int page, int pagesize) {
    if (page > 0) {
      _page = page;
    }
    if (pagesize > 0) {
      _pagesize = pagesize;
    }
    return this;
  }

  /// int count = LIMIT
  BookmarkFilterBuilder top(int count) {
    if (count > 0) {
      _pagesize = count;
    }
    return this;
  }

  /// close parentheses
  BookmarkFilterBuilder get endBlock {
    if (_addedBlocks.needEndBlock[_blockIndex]) {
      parameters[parameters.length - 1].whereString += ' ) ';
    }
    _addedBlocks.needEndBlock.removeAt(_blockIndex);
    _addedBlocks.waitingStartBlock.removeAt(_blockIndex);
    _blockIndex--;
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='name, date'
  ///
  /// Example 2: argFields = ['name', 'date']
  BookmarkFilterBuilder orderBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add(argFields);
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            orderByList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  BookmarkFilterBuilder orderByDesc(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add('$argFields desc ');
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            orderByList.add(' $s desc ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  BookmarkFilterBuilder groupBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        groupByList.add(' $argFields ');
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            groupByList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='name, date'
  ///
  /// Example 2: argFields = ['name', 'date']
  BookmarkFilterBuilder having(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        havingList.add(argFields);
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            havingList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  BookmarkField setField(BookmarkField field, String colName, DbType dbtype) {
    return BookmarkField(this)
      ..param = DbParameter(
          dbType: dbtype,
          columnName: colName,
          wStartBlock: _addedBlocks.waitingStartBlock[_blockIndex]);
  }

  BookmarkField _id;
  BookmarkField get id {
    return _id = setField(_id, 'id', DbType.integer);
  }

  BookmarkField _title;
  BookmarkField get title {
    return _title = setField(_title, 'title', DbType.text);
  }

  BookmarkField _imageUrl;
  BookmarkField get imageUrl {
    return _imageUrl = setField(_imageUrl, 'imageUrl', DbType.text);
  }

  BookmarkField _sourceName;
  BookmarkField get sourceName {
    return _sourceName = setField(_sourceName, 'sourceName', DbType.text);
  }

  BookmarkField _sourceImageUrl;
  BookmarkField get sourceImageUrl {
    return _sourceImageUrl =
        setField(_sourceImageUrl, 'sourceImageUrl', DbType.text);
  }

  BookmarkField _content;
  BookmarkField get content {
    return _content = setField(_content, 'content', DbType.text);
  }

  BookmarkField _dateTime;
  BookmarkField get dateTime {
    return _dateTime = setField(_dateTime, 'dateTime', DbType.datetime);
  }

  BookmarkField _isDeleted;
  BookmarkField get isDeleted {
    return _isDeleted = setField(_isDeleted, 'isDeleted', DbType.bool);
  }

  bool _getIsDeleted;

  void _buildParameters() {
    if (_page > 0 && _pagesize > 0) {
      qparams
        ..limit = _pagesize
        ..offset = (_page - 1) * _pagesize;
    } else {
      qparams
        ..limit = _pagesize
        ..offset = _page;
    }
    for (DbParameter param in parameters) {
      if (param.columnName != null) {
        if (param.value is List && !param.hasParameter) {
          param.value = param.dbType == DbType.text
              ? '\'${param.value.join('\',\'')}\''
              : param.value.join(',');
          whereString += param.whereString
              .replaceAll('{field}', param.columnName)
              .replaceAll('?', param.value.toString());
          param.value = null;
        } else {
          if (param.value is Map<String, dynamic> &&
              param.value['sql'] != null) {
            param
              ..whereString = param.whereString
                  .replaceAll('?', param.value['sql'].toString())
              ..dbType = DbType.integer
              ..value = param.value['args'];
          }
          whereString +=
              param.whereString.replaceAll('{field}', param.columnName);
        }
        if (!param.whereString.contains('?')) {
        } else {
          switch (param.dbType) {
            case DbType.bool:
              param.value =
                  param.value == null ? null : param.value == true ? 1 : 0;
              param.value2 =
                  param.value2 == null ? null : param.value2 == true ? 1 : 0;
              break;
            case DbType.date:
            case DbType.datetime:
            case DbType.datetimeUtc:
              param.value = param.value == null
                  ? null
                  : (param.value as DateTime).millisecondsSinceEpoch;
              param.value2 = param.value2 == null
                  ? null
                  : (param.value2 as DateTime).millisecondsSinceEpoch;
              break;
            default:
          }
          if (param.value != null) {
            if (param.value is List) {
              for (var p in param.value) {
                whereArguments.add(p);
              }
            } else {
              whereArguments.add(param.value);
            }
          }
          if (param.value2 != null) {
            whereArguments.add(param.value2);
          }
        }
      } else {
        whereString += param.whereString;
      }
    }
    if (Bookmark._softDeleteActivated) {
      if (whereString != '') {
        whereString =
            '${!_getIsDeleted ? 'ifnull(isDeleted,0)=0 AND' : ''} ($whereString)';
      } else if (!_getIsDeleted) {
        whereString = 'ifnull(isDeleted,0)=0';
      }
    }

    if (whereString != '') {
      qparams.whereString = whereString;
    }
    qparams
      ..whereArguments = whereArguments
      ..groupBy = groupByList.join(',')
      ..orderBy = orderByList.join(',')
      ..having = havingList.join(',');
  }

  /// Deletes List<Bookmark> bulk by query
  ///
  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    _buildParameters();
    var r = BoolResult();

    if (Bookmark._softDeleteActivated && !hardDelete) {
      r = await _obj._mnBookmark.updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _obj._mnBookmark.delete(qparams);
    }
    return r;
  }

  /// Recover List<Bookmark> bulk by query
  Future<BoolResult> recover() async {
    _getIsDeleted = true;
    _buildParameters();
    print('SQFENTITIY: recover Bookmark bulk invoked');
    return _obj._mnBookmark.updateBatch(qparams, {'isDeleted': 0});
  }

  /// using:
  ///
  /// update({'fieldName': Value})
  ///
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  Future<BoolResult> update(Map<String, dynamic> values) {
    _buildParameters();
    if (qparams.limit > 0 || qparams.offset > 0) {
      qparams.whereString =
          'id IN (SELECT id from bookmark ${qparams.whereString.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _obj._mnBookmark.updateBatch(qparams, values);
  }

  /// This method always returns Bookmark Obj if exist, otherwise returns null
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: toSingle(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>List<Bookmark>
  Future<Bookmark> toSingle(
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    _pagesize = 1;
    _buildParameters();
    final objFuture = _obj._mnBookmark.toList(qparams);
    final data = await objFuture;
    Bookmark obj;
    if (data.isNotEmpty) {
      obj = Bookmark.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// This method returns int. [Bookmark]
  ///
  /// <returns>int
  Future<int> toCount([VoidCallback Function(int c) bookmarkCount]) async {
    _buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final bookmarksFuture = await _obj._mnBookmark.toList(qparams);
    final int count = bookmarksFuture[0]['CNT'] as int;
    if (bookmarkCount != null) {
      bookmarkCount(count);
    }
    return count;
  }

  /// This method returns List<Bookmark> [Bookmark]
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: toList(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: toList(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>List<Bookmark>
  Future<List<Bookmark>> toList(
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    final data = await toMapList();
    final List<Bookmark> bookmarksData = await Bookmark.fromMapList(data,
        preload: preload,
        preloadFields: preloadFields,
        loadParents: loadParents,
        loadedFields: loadedFields,
        setDefaultValues: qparams.selectColumns == null);
    return bookmarksData;
  }

  /// This method returns Json String [Bookmark]
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method returns Json String. [Bookmark]
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChildren(false, true));
    }
    return json.encode(list);
  }

  /// This method returns List<dynamic>. [Bookmark]
  ///
  /// <returns>List<dynamic>
  Future<List<dynamic>> toMapList() async {
    _buildParameters();
    return await _obj._mnBookmark.toList(qparams);
  }

  /// This method returns Primary Key List SQL and Parameters retVal = Map<String,dynamic>. [Bookmark]
  ///
  /// retVal['sql'] = SQL statement string, retVal['args'] = whereArguments List<dynamic>;
  ///
  /// <returns>List<String>
  Map<String, dynamic> toListPrimaryKeySQL([bool buildParameters = true]) {
    final Map<String, dynamic> _retVal = <String, dynamic>{};
    if (buildParameters) {
      _buildParameters();
    }
    _retVal['sql'] = 'SELECT `id` FROM bookmark WHERE ${qparams.whereString}';
    _retVal['args'] = qparams.whereArguments;
    return _retVal;
  }

  /// This method returns Primary Key List<int>.
  /// <returns>List<int>
  Future<List<int>> toListPrimaryKey([bool buildParameters = true]) async {
    if (buildParameters) {
      _buildParameters();
    }
    final List<int> idData = <int>[];
    qparams.selectColumns = ['id'];
    final idFuture = await _obj._mnBookmark.toList(qparams);

    final int count = idFuture.length;
    for (int i = 0; i < count; i++) {
      idData.add(idFuture[i]['id'] as int);
    }
    return idData;
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..  [Bookmark]
  ///
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  Future<List<dynamic>> toListObject() async {
    _buildParameters();

    final objectFuture = _obj._mnBookmark.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  ///
  /// Sample usage: await Bookmark.select(columnsToSelect: ['columnName']).toListString()
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o) listString]) async {
    _buildParameters();

    final objectFuture = _obj._mnBookmark.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns[0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion BookmarkFilterBuilder

// region BookmarkFields
class BookmarkFields {
  static TableField _fId;
  static TableField get id {
    return _fId = _fId ?? SqlSyntax.setField(_fId, 'id', DbType.integer);
  }

  static TableField _fTitle;
  static TableField get title {
    return _fTitle =
        _fTitle ?? SqlSyntax.setField(_fTitle, 'title', DbType.text);
  }

  static TableField _fImageUrl;
  static TableField get imageUrl {
    return _fImageUrl =
        _fImageUrl ?? SqlSyntax.setField(_fImageUrl, 'imageUrl', DbType.text);
  }

  static TableField _fSourceName;
  static TableField get sourceName {
    return _fSourceName = _fSourceName ??
        SqlSyntax.setField(_fSourceName, 'sourceName', DbType.text);
  }

  static TableField _fSourceImageUrl;
  static TableField get sourceImageUrl {
    return _fSourceImageUrl = _fSourceImageUrl ??
        SqlSyntax.setField(_fSourceImageUrl, 'sourceImageUrl', DbType.text);
  }

  static TableField _fContent;
  static TableField get content {
    return _fContent =
        _fContent ?? SqlSyntax.setField(_fContent, 'content', DbType.text);
  }

  static TableField _fDateTime;
  static TableField get dateTime {
    return _fDateTime = _fDateTime ??
        SqlSyntax.setField(_fDateTime, 'dateTime', DbType.datetime);
  }

  static TableField _fIsDeleted;
  static TableField get isDeleted {
    return _fIsDeleted = _fIsDeleted ??
        SqlSyntax.setField(_fIsDeleted, 'isDeleted', DbType.integer);
  }
}
// endregion BookmarkFields

//region BookmarkManager
class BookmarkManager extends SqfEntityProvider {
  BookmarkManager()
      : super(DbModel(),
            tableName: _tableName,
            primaryKeyList: _primaryKeyList,
            whereStr: _whereStr);
  static final String _tableName = 'bookmark';
  static final List<String> _primaryKeyList = ['id'];
  static final String _whereStr = 'id=?';
}

//endregion BookmarkManager
// region Cache
class Cache {
  Cache(
      {this.id,
      this.title,
      this.imageUrl,
      this.sourceName,
      this.sourceImageUrl,
      this.content,
      this.dateTime}) {
    _setDefaultValues();
  }
  Cache.withFields(this.title, this.imageUrl, this.sourceName,
      this.sourceImageUrl, this.content, this.dateTime) {
    _setDefaultValues();
  }
  Cache.withId(this.id, this.title, this.imageUrl, this.sourceName,
      this.sourceImageUrl, this.content, this.dateTime) {
    _setDefaultValues();
  }
  Cache.fromMap(Map<String, dynamic> o, {bool setDefaultValues = true}) {
    if (setDefaultValues) {
      _setDefaultValues();
    }
    id = int.tryParse(o['id'].toString());
    if (o['title'] != null) {
      title = o['title'] as String;
    }
    if (o['imageUrl'] != null) {
      imageUrl = o['imageUrl'] as String;
    }
    if (o['sourceName'] != null) {
      sourceName = o['sourceName'] as String;
    }
    if (o['sourceImageUrl'] != null) {
      sourceImageUrl = o['sourceImageUrl'] as String;
    }
    if (o['content'] != null) {
      content = o['content'] as String;
    }
    if (o['dateTime'] != null) {
      dateTime = int.tryParse(o['dateTime'].toString()) != null
          ? DateTime.fromMillisecondsSinceEpoch(
              int.tryParse(o['dateTime'].toString()))
          : DateTime.tryParse(o['dateTime'].toString());
    }
  }
  // FIELDS (Cache)
  int id;
  String title;
  String imageUrl;
  String sourceName;
  String sourceImageUrl;
  String content;
  DateTime dateTime;

  BoolResult saveResult;
  // end FIELDS (Cache)

  static const bool _softDeleteActivated = false;
  CacheManager __mnCache;

  CacheManager get _mnCache {
    return __mnCache = __mnCache ?? CacheManager();
  }

  // METHODS
  Map<String, dynamic> toMap(
      {bool forQuery = false, bool forJson = false, bool forView = false}) {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (title != null) {
      map['title'] = title;
    }

    if (imageUrl != null) {
      map['imageUrl'] = imageUrl;
    }

    if (sourceName != null) {
      map['sourceName'] = sourceName;
    }

    if (sourceImageUrl != null) {
      map['sourceImageUrl'] = sourceImageUrl;
    }

    if (content != null) {
      map['content'] = content;
    }

    if (dateTime != null) {
      map['dateTime'] = forJson
          ? dateTime.toString()
          : forQuery ? dateTime.millisecondsSinceEpoch : dateTime;
    }

    return map;
  }

  Future<Map<String, dynamic>> toMapWithChildren(
      [bool forQuery = false,
      bool forJson = false,
      bool forView = false]) async {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (title != null) {
      map['title'] = title;
    }

    if (imageUrl != null) {
      map['imageUrl'] = imageUrl;
    }

    if (sourceName != null) {
      map['sourceName'] = sourceName;
    }

    if (sourceImageUrl != null) {
      map['sourceImageUrl'] = sourceImageUrl;
    }

    if (content != null) {
      map['content'] = content;
    }

    if (dateTime != null) {
      map['dateTime'] = forJson
          ? dateTime.toString()
          : forQuery ? dateTime.millisecondsSinceEpoch : dateTime;
    }

    return map;
  }

  /// This method returns Json String [Cache]
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method returns Json String [Cache]
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChildren(false, true));
  }

  List<dynamic> toArgs() {
    return [
      title,
      imageUrl,
      sourceName,
      sourceImageUrl,
      content,
      dateTime != null ? dateTime.millisecondsSinceEpoch : null
    ];
  }

  List<dynamic> toArgsWithIds() {
    return [
      id,
      title,
      imageUrl,
      sourceName,
      sourceImageUrl,
      content,
      dateTime != null ? dateTime.millisecondsSinceEpoch : null
    ];
  }

  static Future<List<Cache>> fromWebUrl(String url,
      {Map<String, String> headers}) async {
    try {
      final response = await http.get(url, headers: headers);
      return await fromJson(response.body);
    } catch (e) {
      print('SQFENTITY ERROR Cache.fromWebUrl: ErrorMessage: ${e.toString()}');
      return null;
    }
  }

  Future<http.Response> postUrl(String url, {Map<String, String> headers}) {
    return http.post(url, headers: headers, body: toJson());
  }

  static Future<List<Cache>> fromJson(String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <Cache>[];
    try {
      objList = list
          .map((cache) => Cache.fromMap(cache as Map<String, dynamic>))
          .toList();
    } catch (e) {
      print('SQFENTITY ERROR Cache.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  static Future<List<Cache>> fromMapList(List<dynamic> data,
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields,
      bool setDefaultValues = true}) async {
    final List<Cache> objList = <Cache>[];
    loadedFields = loadedFields ?? [];
    for (final map in data) {
      final obj = Cache.fromMap(map as Map<String, dynamic>,
          setDefaultValues: setDefaultValues);

      objList.add(obj);
    }
    return objList;
  }

  /// returns Cache by ID if exist, otherwise returns null
  ///
  /// Primary Keys: int id
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: getById(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: getById(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>returns Cache if exist, otherwise returns null
  Future<Cache> getById(int id,
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    if (id == null) {
      return null;
    }
    Cache obj;
    final data = await _mnCache.getById([id]);
    if (data.length != 0) {
      obj = Cache.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the (Cache) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record

  /// <returns>Returns id
  Future<int> save() async {
    if (id == null || id == 0) {
      id = await _mnCache.insert(this);
    } else {
      // id= await _upsert(); // removed in sqfentity_gen 1.3.0+6
      await _mnCache.update(this);
    }

    return id;
  }

  /// saveAs Cache. Returns a new Primary Key value of Cache

  /// <returns>Returns a new Primary Key value of Cache
  Future<int> saveAs() async {
    id = null;

    return save();
  }

  /// saveAll method saves the sent List<Cache> as a bulk in one transaction
  ///
  /// Returns a <List<BoolResult>>
  static Future<List<dynamic>> saveAll(List<Cache> caches) async {
    // final results = _mnCache.saveAll('INSERT OR REPLACE INTO cache (id,title, imageUrl, sourceName, sourceImageUrl, content, dateTime)  VALUES (?,?,?,?,?,?,?)',caches);
    // return results; removed in sqfentity_gen 1.3.0+6
    await DbModel().batchStart();
    for (final obj in caches) {
      await obj.save();
    }
    //    return DbModel().batchCommit();
    final result = await DbModel().batchCommit();
    for (int i = 0; i < caches.length; i++) {
      if (caches[i].id == null) {
        caches[i].id = result[i] as int;
      }
    }

    return result;
  }

  /// Updates if the record exists, otherwise adds a new row

  /// <returns>Returns id
  Future<int> upsert() async {
    try {
      if (await _mnCache.rawInsert(
              'INSERT OR REPLACE INTO cache (id,title, imageUrl, sourceName, sourceImageUrl, content, dateTime)  VALUES (?,?,?,?,?,?,?)',
              [
                id,
                title,
                imageUrl,
                sourceName,
                sourceImageUrl,
                content,
                dateTime != null ? dateTime.millisecondsSinceEpoch : null
              ]) ==
          1) {
        saveResult = BoolResult(
            success: true, successMessage: 'Cache id=$id updated successfully');
      } else {
        saveResult = BoolResult(
            success: false, errorMessage: 'Cache id=$id did not update');
      }
      return id;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage: 'Cache Save failed. Error: ${e.toString()}');
      return 0;
    }
  }

  /// inserts or replaces the sent List<<Cache>> as a bulk in one transaction.
  ///
  /// upsertAll() method is faster then saveAll() method. upsertAll() should be used when you are sure that the primary key is greater than zero
  ///
  /// Returns a BoolCommitResult
  Future<BoolCommitResult> upsertAll(List<Cache> caches) async {
    final results = await _mnCache.rawInsertAll(
        'INSERT OR REPLACE INTO cache (id,title, imageUrl, sourceName, sourceImageUrl, content, dateTime)  VALUES (?,?,?,?,?,?,?)',
        caches);
    return results;
  }

  /// Deletes Cache

  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    print('SQFENTITIY: delete Cache invoked (id=$id)');
    if (!_softDeleteActivated || hardDelete) {
      return _mnCache
          .delete(QueryParams(whereString: 'id=?', whereArguments: [id]));
    } else {
      return _mnCache.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 1});
    }
  }

  CacheFilterBuilder select({List<String> columnsToSelect, bool getIsDeleted}) {
    return CacheFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect;
  }

  CacheFilterBuilder distinct(
      {List<String> columnsToSelect, bool getIsDeleted}) {
    return CacheFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {}
  // END METHODS
  // CUSTOM CODES
  /*
      you must define customCode property of your SqfEntityTable constant for ex:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODES
}
// endregion cache

// region CacheField
class CacheField extends SearchCriteria {
  CacheField(this.cacheFB) {
    param = DbParameter();
  }
  DbParameter param;
  String _waitingNot = '';
  CacheFilterBuilder cacheFB;

  CacheField get not {
    _waitingNot = ' NOT ';
    return this;
  }

  CacheFilterBuilder equals(dynamic pValue) {
    param.expression = '=';
    cacheFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, cacheFB.parameters, param, SqlSyntax.EQuals,
            cacheFB._addedBlocks)
        : setCriteria(pValue, cacheFB.parameters, param, SqlSyntax.NotEQuals,
            cacheFB._addedBlocks);
    _waitingNot = '';
    cacheFB._addedBlocks.needEndBlock[cacheFB._blockIndex] =
        cacheFB._addedBlocks.retVal;
    return cacheFB;
  }

  CacheFilterBuilder equalsOrNull(dynamic pValue) {
    param.expression = '=';
    cacheFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, cacheFB.parameters, param, SqlSyntax.EQualsOrNull,
            cacheFB._addedBlocks)
        : setCriteria(pValue, cacheFB.parameters, param,
            SqlSyntax.NotEQualsOrNull, cacheFB._addedBlocks);
    _waitingNot = '';
    cacheFB._addedBlocks.needEndBlock[cacheFB._blockIndex] =
        cacheFB._addedBlocks.retVal;
    return cacheFB;
  }

  CacheFilterBuilder isNull() {
    cacheFB._addedBlocks = setCriteria(
        0,
        cacheFB.parameters,
        param,
        SqlSyntax.IsNULL.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        cacheFB._addedBlocks);
    _waitingNot = '';
    cacheFB._addedBlocks.needEndBlock[cacheFB._blockIndex] =
        cacheFB._addedBlocks.retVal;
    return cacheFB;
  }

  CacheFilterBuilder contains(dynamic pValue) {
    if (pValue != null) {
      cacheFB._addedBlocks = setCriteria(
          '%${pValue.toString()}%',
          cacheFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          cacheFB._addedBlocks);
      _waitingNot = '';
      cacheFB._addedBlocks.needEndBlock[cacheFB._blockIndex] =
          cacheFB._addedBlocks.retVal;
    }
    return cacheFB;
  }

  CacheFilterBuilder startsWith(dynamic pValue) {
    if (pValue != null) {
      cacheFB._addedBlocks = setCriteria(
          '${pValue.toString()}%',
          cacheFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          cacheFB._addedBlocks);
      _waitingNot = '';
      cacheFB._addedBlocks.needEndBlock[cacheFB._blockIndex] =
          cacheFB._addedBlocks.retVal;
      cacheFB._addedBlocks.needEndBlock[cacheFB._blockIndex] =
          cacheFB._addedBlocks.retVal;
    }
    return cacheFB;
  }

  CacheFilterBuilder endsWith(dynamic pValue) {
    if (pValue != null) {
      cacheFB._addedBlocks = setCriteria(
          '%${pValue.toString()}',
          cacheFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          cacheFB._addedBlocks);
      _waitingNot = '';
      cacheFB._addedBlocks.needEndBlock[cacheFB._blockIndex] =
          cacheFB._addedBlocks.retVal;
    }
    return cacheFB;
  }

  CacheFilterBuilder between(dynamic pFirst, dynamic pLast) {
    if (pFirst != null && pLast != null) {
      cacheFB._addedBlocks = setCriteria(
          pFirst,
          cacheFB.parameters,
          param,
          SqlSyntax.Between.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          cacheFB._addedBlocks,
          pLast);
    } else if (pFirst != null) {
      if (_waitingNot != '') {
        cacheFB._addedBlocks = setCriteria(pFirst, cacheFB.parameters, param,
            SqlSyntax.LessThan, cacheFB._addedBlocks);
      } else {
        cacheFB._addedBlocks = setCriteria(pFirst, cacheFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, cacheFB._addedBlocks);
      }
    } else if (pLast != null) {
      if (_waitingNot != '') {
        cacheFB._addedBlocks = setCriteria(pLast, cacheFB.parameters, param,
            SqlSyntax.GreaterThan, cacheFB._addedBlocks);
      } else {
        cacheFB._addedBlocks = setCriteria(pLast, cacheFB.parameters, param,
            SqlSyntax.LessThanOrEquals, cacheFB._addedBlocks);
      }
    }
    _waitingNot = '';
    cacheFB._addedBlocks.needEndBlock[cacheFB._blockIndex] =
        cacheFB._addedBlocks.retVal;
    return cacheFB;
  }

  CacheFilterBuilder greaterThan(dynamic pValue) {
    param.expression = '>';
    cacheFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, cacheFB.parameters, param, SqlSyntax.GreaterThan,
            cacheFB._addedBlocks)
        : setCriteria(pValue, cacheFB.parameters, param,
            SqlSyntax.LessThanOrEquals, cacheFB._addedBlocks);
    _waitingNot = '';
    cacheFB._addedBlocks.needEndBlock[cacheFB._blockIndex] =
        cacheFB._addedBlocks.retVal;
    return cacheFB;
  }

  CacheFilterBuilder lessThan(dynamic pValue) {
    param.expression = '<';
    cacheFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, cacheFB.parameters, param, SqlSyntax.LessThan,
            cacheFB._addedBlocks)
        : setCriteria(pValue, cacheFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, cacheFB._addedBlocks);
    _waitingNot = '';
    cacheFB._addedBlocks.needEndBlock[cacheFB._blockIndex] =
        cacheFB._addedBlocks.retVal;
    return cacheFB;
  }

  CacheFilterBuilder greaterThanOrEquals(dynamic pValue) {
    param.expression = '>=';
    cacheFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, cacheFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, cacheFB._addedBlocks)
        : setCriteria(pValue, cacheFB.parameters, param, SqlSyntax.LessThan,
            cacheFB._addedBlocks);
    _waitingNot = '';
    cacheFB._addedBlocks.needEndBlock[cacheFB._blockIndex] =
        cacheFB._addedBlocks.retVal;
    return cacheFB;
  }

  CacheFilterBuilder lessThanOrEquals(dynamic pValue) {
    param.expression = '<=';
    cacheFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, cacheFB.parameters, param,
            SqlSyntax.LessThanOrEquals, cacheFB._addedBlocks)
        : setCriteria(pValue, cacheFB.parameters, param, SqlSyntax.GreaterThan,
            cacheFB._addedBlocks);
    _waitingNot = '';
    cacheFB._addedBlocks.needEndBlock[cacheFB._blockIndex] =
        cacheFB._addedBlocks.retVal;
    return cacheFB;
  }

  CacheFilterBuilder inValues(dynamic pValue) {
    cacheFB._addedBlocks = setCriteria(
        pValue,
        cacheFB.parameters,
        param,
        SqlSyntax.IN.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        cacheFB._addedBlocks);
    _waitingNot = '';
    cacheFB._addedBlocks.needEndBlock[cacheFB._blockIndex] =
        cacheFB._addedBlocks.retVal;
    return cacheFB;
  }
}
// endregion CacheField

// region CacheFilterBuilder
class CacheFilterBuilder extends SearchCriteria {
  CacheFilterBuilder(Cache obj) {
    whereString = '';
    qparams = QueryParams();
    parameters = <DbParameter>[];
    orderByList = <String>[];
    groupByList = <String>[];
    _addedBlocks = AddedBlocks(<bool>[], <bool>[]);
    _addedBlocks.needEndBlock.add(false);
    _addedBlocks.waitingStartBlock.add(false);
    _pagesize = 0;
    _page = 0;
    _obj = obj;
  }
  AddedBlocks _addedBlocks;
  int _blockIndex = 0;
  List<DbParameter> parameters;
  List<String> orderByList;
  Cache _obj;
  QueryParams qparams;
  int _pagesize;
  int _page;

  /// put the sql keyword 'AND'
  CacheFilterBuilder get and {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' AND ';
    }
    return this;
  }

  /// put the sql keyword 'OR'
  CacheFilterBuilder get or {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' OR ';
    }
    return this;
  }

  /// open parentheses
  CacheFilterBuilder get startBlock {
    _addedBlocks.waitingStartBlock.add(true);
    _addedBlocks.needEndBlock.add(false);
    _blockIndex++;
    if (_blockIndex > 1) {
      _addedBlocks.needEndBlock[_blockIndex - 1] = true;
    }
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  CacheFilterBuilder where(String whereCriteria, {dynamic parameterValue}) {
    if (whereCriteria != null && whereCriteria != '') {
      final DbParameter param = DbParameter(
          columnName: parameterValue == null ? null : '',
          hasParameter: parameterValue != null);
      _addedBlocks = setCriteria(parameterValue ?? 0, parameters, param,
          '($whereCriteria)', _addedBlocks);
      _addedBlocks.needEndBlock[_blockIndex] = _addedBlocks.retVal;
    }
    return this;
  }

  /// page = page number,
  ///
  /// pagesize = row(s) per page
  CacheFilterBuilder page(int page, int pagesize) {
    if (page > 0) {
      _page = page;
    }
    if (pagesize > 0) {
      _pagesize = pagesize;
    }
    return this;
  }

  /// int count = LIMIT
  CacheFilterBuilder top(int count) {
    if (count > 0) {
      _pagesize = count;
    }
    return this;
  }

  /// close parentheses
  CacheFilterBuilder get endBlock {
    if (_addedBlocks.needEndBlock[_blockIndex]) {
      parameters[parameters.length - 1].whereString += ' ) ';
    }
    _addedBlocks.needEndBlock.removeAt(_blockIndex);
    _addedBlocks.waitingStartBlock.removeAt(_blockIndex);
    _blockIndex--;
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='name, date'
  ///
  /// Example 2: argFields = ['name', 'date']
  CacheFilterBuilder orderBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add(argFields);
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            orderByList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  CacheFilterBuilder orderByDesc(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add('$argFields desc ');
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            orderByList.add(' $s desc ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  CacheFilterBuilder groupBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        groupByList.add(' $argFields ');
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            groupByList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='name, date'
  ///
  /// Example 2: argFields = ['name', 'date']
  CacheFilterBuilder having(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        havingList.add(argFields);
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            havingList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  CacheField setField(CacheField field, String colName, DbType dbtype) {
    return CacheField(this)
      ..param = DbParameter(
          dbType: dbtype,
          columnName: colName,
          wStartBlock: _addedBlocks.waitingStartBlock[_blockIndex]);
  }

  CacheField _id;
  CacheField get id {
    return _id = setField(_id, 'id', DbType.integer);
  }

  CacheField _title;
  CacheField get title {
    return _title = setField(_title, 'title', DbType.text);
  }

  CacheField _imageUrl;
  CacheField get imageUrl {
    return _imageUrl = setField(_imageUrl, 'imageUrl', DbType.text);
  }

  CacheField _sourceName;
  CacheField get sourceName {
    return _sourceName = setField(_sourceName, 'sourceName', DbType.text);
  }

  CacheField _sourceImageUrl;
  CacheField get sourceImageUrl {
    return _sourceImageUrl =
        setField(_sourceImageUrl, 'sourceImageUrl', DbType.text);
  }

  CacheField _content;
  CacheField get content {
    return _content = setField(_content, 'content', DbType.text);
  }

  CacheField _dateTime;
  CacheField get dateTime {
    return _dateTime = setField(_dateTime, 'dateTime', DbType.datetime);
  }

  bool _getIsDeleted;

  void _buildParameters() {
    if (_page > 0 && _pagesize > 0) {
      qparams
        ..limit = _pagesize
        ..offset = (_page - 1) * _pagesize;
    } else {
      qparams
        ..limit = _pagesize
        ..offset = _page;
    }
    for (DbParameter param in parameters) {
      if (param.columnName != null) {
        if (param.value is List && !param.hasParameter) {
          param.value = param.dbType == DbType.text
              ? '\'${param.value.join('\',\'')}\''
              : param.value.join(',');
          whereString += param.whereString
              .replaceAll('{field}', param.columnName)
              .replaceAll('?', param.value.toString());
          param.value = null;
        } else {
          if (param.value is Map<String, dynamic> &&
              param.value['sql'] != null) {
            param
              ..whereString = param.whereString
                  .replaceAll('?', param.value['sql'].toString())
              ..dbType = DbType.integer
              ..value = param.value['args'];
          }
          whereString +=
              param.whereString.replaceAll('{field}', param.columnName);
        }
        if (!param.whereString.contains('?')) {
        } else {
          switch (param.dbType) {
            case DbType.bool:
              param.value =
                  param.value == null ? null : param.value == true ? 1 : 0;
              param.value2 =
                  param.value2 == null ? null : param.value2 == true ? 1 : 0;
              break;
            case DbType.date:
            case DbType.datetime:
            case DbType.datetimeUtc:
              param.value = param.value == null
                  ? null
                  : (param.value as DateTime).millisecondsSinceEpoch;
              param.value2 = param.value2 == null
                  ? null
                  : (param.value2 as DateTime).millisecondsSinceEpoch;
              break;
            default:
          }
          if (param.value != null) {
            if (param.value is List) {
              for (var p in param.value) {
                whereArguments.add(p);
              }
            } else {
              whereArguments.add(param.value);
            }
          }
          if (param.value2 != null) {
            whereArguments.add(param.value2);
          }
        }
      } else {
        whereString += param.whereString;
      }
    }
    if (Cache._softDeleteActivated) {
      if (whereString != '') {
        whereString =
            '${!_getIsDeleted ? 'ifnull(isDeleted,0)=0 AND' : ''} ($whereString)';
      } else if (!_getIsDeleted) {
        whereString = 'ifnull(isDeleted,0)=0';
      }
    }

    if (whereString != '') {
      qparams.whereString = whereString;
    }
    qparams
      ..whereArguments = whereArguments
      ..groupBy = groupByList.join(',')
      ..orderBy = orderByList.join(',')
      ..having = havingList.join(',');
  }

  /// Deletes List<Cache> bulk by query
  ///
  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    _buildParameters();
    var r = BoolResult();

    if (Cache._softDeleteActivated && !hardDelete) {
      r = await _obj._mnCache.updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _obj._mnCache.delete(qparams);
    }
    return r;
  }

  /// using:
  ///
  /// update({'fieldName': Value})
  ///
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  Future<BoolResult> update(Map<String, dynamic> values) {
    _buildParameters();
    if (qparams.limit > 0 || qparams.offset > 0) {
      qparams.whereString =
          'id IN (SELECT id from cache ${qparams.whereString.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _obj._mnCache.updateBatch(qparams, values);
  }

  /// This method always returns Cache Obj if exist, otherwise returns null
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: toSingle(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>List<Cache>
  Future<Cache> toSingle(
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    _pagesize = 1;
    _buildParameters();
    final objFuture = _obj._mnCache.toList(qparams);
    final data = await objFuture;
    Cache obj;
    if (data.isNotEmpty) {
      obj = Cache.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// This method returns int. [Cache]
  ///
  /// <returns>int
  Future<int> toCount([VoidCallback Function(int c) cacheCount]) async {
    _buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final cachesFuture = await _obj._mnCache.toList(qparams);
    final int count = cachesFuture[0]['CNT'] as int;
    if (cacheCount != null) {
      cacheCount(count);
    }
    return count;
  }

  /// This method returns List<Cache> [Cache]
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: toList(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: toList(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>List<Cache>
  Future<List<Cache>> toList(
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    final data = await toMapList();
    final List<Cache> cachesData = await Cache.fromMapList(data,
        preload: preload,
        preloadFields: preloadFields,
        loadParents: loadParents,
        loadedFields: loadedFields,
        setDefaultValues: qparams.selectColumns == null);
    return cachesData;
  }

  /// This method returns Json String [Cache]
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method returns Json String. [Cache]
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChildren(false, true));
    }
    return json.encode(list);
  }

  /// This method returns List<dynamic>. [Cache]
  ///
  /// <returns>List<dynamic>
  Future<List<dynamic>> toMapList() async {
    _buildParameters();
    return await _obj._mnCache.toList(qparams);
  }

  /// This method returns Primary Key List SQL and Parameters retVal = Map<String,dynamic>. [Cache]
  ///
  /// retVal['sql'] = SQL statement string, retVal['args'] = whereArguments List<dynamic>;
  ///
  /// <returns>List<String>
  Map<String, dynamic> toListPrimaryKeySQL([bool buildParameters = true]) {
    final Map<String, dynamic> _retVal = <String, dynamic>{};
    if (buildParameters) {
      _buildParameters();
    }
    _retVal['sql'] = 'SELECT `id` FROM cache WHERE ${qparams.whereString}';
    _retVal['args'] = qparams.whereArguments;
    return _retVal;
  }

  /// This method returns Primary Key List<int>.
  /// <returns>List<int>
  Future<List<int>> toListPrimaryKey([bool buildParameters = true]) async {
    if (buildParameters) {
      _buildParameters();
    }
    final List<int> idData = <int>[];
    qparams.selectColumns = ['id'];
    final idFuture = await _obj._mnCache.toList(qparams);

    final int count = idFuture.length;
    for (int i = 0; i < count; i++) {
      idData.add(idFuture[i]['id'] as int);
    }
    return idData;
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..  [Cache]
  ///
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  Future<List<dynamic>> toListObject() async {
    _buildParameters();

    final objectFuture = _obj._mnCache.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  ///
  /// Sample usage: await Cache.select(columnsToSelect: ['columnName']).toListString()
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o) listString]) async {
    _buildParameters();

    final objectFuture = _obj._mnCache.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns[0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion CacheFilterBuilder

// region CacheFields
class CacheFields {
  static TableField _fId;
  static TableField get id {
    return _fId = _fId ?? SqlSyntax.setField(_fId, 'id', DbType.integer);
  }

  static TableField _fTitle;
  static TableField get title {
    return _fTitle =
        _fTitle ?? SqlSyntax.setField(_fTitle, 'title', DbType.text);
  }

  static TableField _fImageUrl;
  static TableField get imageUrl {
    return _fImageUrl =
        _fImageUrl ?? SqlSyntax.setField(_fImageUrl, 'imageUrl', DbType.text);
  }

  static TableField _fSourceName;
  static TableField get sourceName {
    return _fSourceName = _fSourceName ??
        SqlSyntax.setField(_fSourceName, 'sourceName', DbType.text);
  }

  static TableField _fSourceImageUrl;
  static TableField get sourceImageUrl {
    return _fSourceImageUrl = _fSourceImageUrl ??
        SqlSyntax.setField(_fSourceImageUrl, 'sourceImageUrl', DbType.text);
  }

  static TableField _fContent;
  static TableField get content {
    return _fContent =
        _fContent ?? SqlSyntax.setField(_fContent, 'content', DbType.text);
  }

  static TableField _fDateTime;
  static TableField get dateTime {
    return _fDateTime = _fDateTime ??
        SqlSyntax.setField(_fDateTime, 'dateTime', DbType.datetime);
  }
}
// endregion CacheFields

//region CacheManager
class CacheManager extends SqfEntityProvider {
  CacheManager()
      : super(DbModel(),
            tableName: _tableName,
            primaryKeyList: _primaryKeyList,
            whereStr: _whereStr);
  static final String _tableName = 'cache';
  static final List<String> _primaryKeyList = ['id'];
  static final String _whereStr = 'id=?';
}

//endregion CacheManager
class DbModelSequenceManager extends SqfEntityProvider {
  DbModelSequenceManager() : super(DbModel());
}
// END OF ENTITIES
